[project]
name = "haydn-info-card"
version = "0.1.0"
description = "Generates the Haydn Quartet Info Card pdf."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.1.8",
    "matplotlib==3.10.0",
    "pdfrw==0.4",
    "pypdf>=5.1.0",
    "reportlab==4.1.0",
]
