[project]
name = "haydn-info-card"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib==3.10.0",
    "pdfrw==0.4",
    "reportlab==4.1.0",
]
